#
# Travis CI config file
#

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry
install:
  - poetry install

# command to run tests
script:
  - poetry run pytest

